name: CI
on:
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check Go version
        run: go version

      - name: Verify module dependencies
        run: go mod tidy && git diff --exit-code go.mod go.sum

      - name: Run tests
        run: go test --cover ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Add Go binaries to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run Security Check
        run: gosec ./...

  style:
    name: Style Checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Install StaticCheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Add Go binaries to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run Static Analysis
        run: staticcheck ./...
